import test from 'node:test';
import assert from 'node:assert/strict';
import {manifestFor,saveGallery} from '../admin/gallery-core.mjs';
import {justifiedLayout} from '../assets/js/gallery.mjs';
const photo={id:'test-photo',src:'/images/gallery/test-photo.jpg',name:' Mountain ',description:' Story ',date:'2026-10-01',tags:'Mountains, mountains, hiking',width:1600,height:1000};
test('metadata normalizes tags and excludes draft-only fields',()=>{const p=manifestFor([{...photo,preview:'blob:private'}]).photos[0];assert.deepEqual(p.tags,['mountains','hiking']);assert.equal(p.name,'Mountain');assert.equal(p.preview,undefined);});
test('invalid names, dates and paths cannot publish',()=>{for(const change of [{name:''},{date:'2026-02-30'},{src:'/outside.jpg'}])assert.throws(()=>manifestFor([{...photo,...change}]));});
test('mixed portrait and landscape rows fit and preserve proportions',()=>{const photos=[photo,{width:700,height:1400},{width:2000,height:800},photo,{width:900,height:1100}];for(const width of [320,700,1200]){const sizes=justifiedLayout(photos,width);sizes.forEach((s,i)=>{assert.ok(s.width<=width);assert.ok(Math.abs(s.width/s.height-photos[i].width/photos[i].height)<.001);});let total=0,h=0;for(const s of sizes){if(h!==s.height){assert.ok(total<=width+.1);total=0;h=s.height;}total+=(total?10:0)+s.width;}assert.ok(total<=width+.1);}});
function mock(existing='original'){const calls=[];const api=async(path,method='GET',body)=>{calls.push({path,method,body});if(path.includes('/git/ref/heads'))return {object:{sha:'head'}};if(path.includes('/git/commits/')&&method==='GET')return {tree:{sha:'base'}};if(path.includes('/contents/'))return {sha:existing};if(path.endsWith('/git/blobs'))return {sha:'blob'};if(path.endsWith('/git/trees'))return {sha:'tree'};if(path.endsWith('/git/commits'))return {sha:'commit'};return {};};return {api,calls};}
test('metadata edits preserve media and commit atomically without force',async()=>{const {api,calls}=mock();await saveGallery(api,[photo],'original',()=>assert.fail('Must not upload an existing photo'));assert.equal(calls.filter(c=>c.path.endsWith('/git/blobs')).length,1);const tree=calls.find(c=>c.path.endsWith('/git/trees')).body;assert.equal(tree.base_tree,'base');assert.equal(tree.tree.length,1);assert.deepEqual(calls.at(-1).body,{sha:'commit',force:false});});
test('concurrent gallery edit rejects before uploads',async()=>{const {api,calls}=mock('changed');await assert.rejects(saveGallery(api,[photo],'original',()=>{}),/gallery changed/);assert.ok(calls.every(c=>c.method==='GET'));});
test('new image and metadata share one commit',async()=>{const {api,calls}=mock();await saveGallery(api,[{...photo,file:{name:'photo.jpg',type:'image/jpeg',size:100}}],'original',async()=> 'encoded');assert.equal(calls.find(c=>c.path.endsWith('/git/trees')).body.tree.length,2);assert.equal(calls.filter(c=>c.path.endsWith('/git/commits')&&c.method==='POST').length,1);});

test('tag selection requires all chosen tags and clearing includes untagged photos',async()=>{const {matchesTags}=await import('../assets/js/gallery.mjs');assert.equal(matchesTags({tags:['snow']},new Set(['snow','wildlife'])),false);assert.equal(matchesTags({tags:['snow','wildlife','mountains']},new Set(['snow','wildlife'])),true);assert.equal(matchesTags({tags:['ocean']},new Set(['snow','wildlife'])),false);assert.equal(matchesTags({},new Set()),true);assert.equal(matchesTags({},new Set(['snow'])),false);});
